# Generated by Django 4.2.1 on 2023-08-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="promotions",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
