# Generated by Django 4.2.1 on 2023-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_review_product_remove_product_promotions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
