# Generated by Django 4.2.1 on 2023-08-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_stripe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.CharField(
                choices=[("PD", "Pending"), ("SC", "Success"), ("FA", "Failed")],
                default="PD",
                max_length=2,
            ),
        ),
    ]
